title = "Wikiotics"
languageCode = "en-us"
baseURL = "/"
cleanDestinationDir = true
disableKinds = ["sitemap", "taxonomy", "taxonomyTerm", "RSS"]
disablePathToLower = true
paginate = 10000

# Because pandoc sometimes returns HTML tables rather than markdown ones
[markup.goldmark.renderer]
unsafe = true
