title = "Wikiotics"
languageCode = "en-us"
baseURL = "/"
cleanDestinationDir = true
disableKinds = ["sitemap", "taxonomy", "taxonomyTerm", "RSS"]
disablePathToLower = true

# While migrating from the old Ductus site, pandoc sometimes returned
# HTML tables rather than markdown ones, so we enable HTML in Markdown
[markup.goldmark.renderer]
unsafe = true
